### ISSUE TITLE
On my device, x axis can't be calibrated.

### ISSUE THREAD

**Issue by steprun** [sunqn/Magnetometer-Auto-Calibration#2]
How can I find thing what caused?

**Comment by antsundq** [comment]
Hi,
You will need to provide some more derails on this issue. 

- What do you mean by "can't be calibrated"?
- How are you trying to calibrate it?
- Measure the *raw* output of the device while rotatating it around all axes and then plot the x and y outputs. What does this look like?

**Comment by steprun** [comment]
Device X axis south position
Raw Data:      3 -87.45  -2.25
Raw with Norm:  0.0237268  -0.691636 -0.0177951
A:  1.0077 2.01069 2.99995, B:   0.973525      1.3518 -0.00638716
Cal data: 0.997435 -0.038864 -0.059772
Cal data * 50: 49.871735 -1.943205 -2.988578

Oppsite position X axis north position
Raw: 69.45 -84.9  -6.6
RaN:  0.549275 -0.671468 -0.052199
Cal:     1.0003 0.00743834 -0.0671223
A: 1.00355 2.01074 3.00071, B: 0.449069   1.35758 0.0895115
Cal2: 1.000296 0.007438 -0.067122
Cal data * 50: 50.014779 0.371917 -3.356116

X axis cal values almost aren't changed, Maybe offset or scale for X was something wrong.

**Comment by antsundq** [comment]
Sorry, but I cannot draw any conclusion form that. 
In order for the model to work you need more than one or two data points. 

Can you hook up the sensor to get the raw xyz-values into a logfile (maybe 1000 data pairs) and plot the x and y values in a graph?

**Comment by steprun** [comment]
Can I log file to you? Is raw data log file enough?

**Comment by steprun** [comment]
[magraw_1.log](https://github.com/antsundq/Magnetometer-Auto-Calibration/files/7963527/magraw_1.log)

there are 3268 data in file, X Y Z align

**Comment by antsundq** [comment]
So if you plot the data as I wrote, you will get something like this:
![image](https://user-images.githubusercontent.com/40723774/151674153-7d70da00-f4fd-413a-a23b-ba8238d60a71.png)

There you see that the x-axis offset is huge in your device. In fact it seem to be that all your points are in the positive half plane in x. I'm not sure how well the algorithm handles such a case, but if it can handle it the learning time will be very long. 

I would suggest that you preprocess your raw data to compensate for the offset. You can try to simply take x=x_raw-30 as your input to the model and it should work.

**Comment by antsundq** [comment]
Sorry for the missleading axis labels
![image](https://user-images.githubusercontent.com/40723774/151674261-1c268a19-c6dc-4d46-bd2c-f6abdea5a204.png)

**Comment by steprun** [comment]
If many devices, how to find the huge offset values for every one?

**Comment by antsundq** [comment]
The best way to solve it completely depends on the context. 

Magnetometers will always have offsets and biases which needs to be compensated for. 

I think this auto-cal algorithm should handle even the cases with large offsets, but it would require more data. It would probably be good to store the values between restarts to reduce the startup time. 

You could also do a rough 6-point calibration manually to handle the offsets of each sensor axis and make a rough hard coded compensation.

You could also use a better sensor which would be factory calibrated.

**Comment by steprun** [comment]
I found if bias >= 100uT using mag_raw_data_long.txt，algorithm would fail.

**Comment by steprun** [comment]
data_x = file_data_x * 0.7 - 100
data_y = file_data_y * 1.0 - 20
data_z = file_data_z * 0.9 + 10
if data convert like above, algorithm will fail.
But bias less than abs(100), it works.
